name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Set Android SDK environment variables
      run: |
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
    
    - name: Install required Android components
      run: |
        yes | sdkmanager "platforms;android-34"
        sdkmanager "build-tools;34.0.0"
        sdkmanager "platform-tools"
        sdkmanager "cmdline-tools;latest"
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      env:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx4g"
      run: |
        ./gradlew clean
        ./gradlew assembleDebug --stacktrace --info
