name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        build-tools-version: '34.0.0'
        platform-version: '34'
        cmake-version: '3.22.1'
        ndk-version: '25.2.9519653'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      env:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx4g"
      run: |
        ./gradlew clean
        ./gradlew assembleDebug --stacktrace --info
